name: anon-blog-client CI

on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup node
      uses: actions/setup-node@v1
      with:
        node-version: 12

    - run: npm install
    - run: npm run build --if-present
      env:
        CI: true

    - name: deploying via ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        script: |
          cd anon-blog-client
          git pull origin master
          docker kill client
          docker rm client
          docker build -t anon-blog-client .
          docker run --publish 80:3000 --detach --name client anon-blog-client