name: anon-blog-client CI

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup node
      uses: actions/setup-node@v1
      with:
        node-version: 12

    - run: npm install
    - run: npm run build --if-present
      env:
        CI: true